/**
 * Created by nan on 2018/7/11.
 */
Ext.define('CGP.text.testuxtreecombo.config.Config', {
    statics: {
        data: [
            {"_id": "133861", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "shopping-bag", "name": "DynamicSizeBag", "category": "133860", "leaf": false},
            {"_id": "133913", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "shoppingBagSingle", "name": "shopping bag single", "category": "138839", "leaf": true},
            {"_id": "133915", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "shoppingBagDouble", "name": "shopping bag double", "category": "138839", "leaf": true},
            {"_id": "133916", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "shoppingBagFront", "name": "shopping bag front", "category": "138839", "leaf": true},
            {"_id": "133917", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "shoppingBagBack", "name": "Shopping Bag Back", "category": "138839", "leaf": true},
            {"_id": "133934", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test", "name": "test", "category": "393848", "leaf": false},
            {"_id": "135083", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "invitation card", "name": "invitation card", "category": "133860", "leaf": true},
            {"_id": "136208", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "InvitationCard", "name": "InvitationCard", "category": "133860", "leaf": false},
            {"_id": "136646", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test1", "name": "test1", "category": "144073", "leaf": true},
            {"_id": "136788", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "favorBox", "name": "favorBox", "category": "140677", "leaf": false},
            {"_id": "136973", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "shoppingBag", "name": "shoppingBag", "category": "138839", "leaf": true},
            {"_id": "148066", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "shoppingBagLine", "name": "shopping Bag Line", "category": "138839", "leaf": true},
            {"_id": "148068", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "ShoppingBag2", "name": "Shopping Bag 2", "category": "138839", "leaf": true},
            {"_id": "154361", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Card", "name": "Card", "category": "154360", "leaf": true},
            {"_id": "154398", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "StarCard", "name": "Star Card", "category": "154360", "leaf": true},
            {"_id": "156098", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "horizontalInvitaion", "name": "horizontalInvitaion", "category": "133860", "leaf": false},
            {"_id": "114798", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "mosaic_favor_box_mainMateial", "name": "mosaic favor box", "category": "140677", "leaf": true},
            {"_id": "179452", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test", "name": "test", "category": "144073", "leaf": true},
            {"_id": "185157", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "invitationCard-envelope", "name": "invitationCard-envelope", "category": "133860", "leaf": true},
            {"_id": "185404", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "InvitationCardNew", "name": "InvitationCardNew", "category": "133860", "leaf": false},
            {"_id": "185562", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "invitationCardSticker", "name": "invitationCardSticker", "category": "133860", "leaf": true},
            {"_id": "185600", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "invitationCardProduct", "name": "invitationCardProduct", "category": "133860", "leaf": false},
            {"_id": "187005", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "invitationCard-envelope-spu", "name": "invitationCard-envelope-spu", "category": "133860", "leaf": true},
            {"_id": "187129", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test3", "name": "test3", "category": "144073", "leaf": true},
            {"_id": "188794", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Puzzle", "name": "Puzzle", "category": "188784", "leaf": false},
            {"_id": "188804", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "newShoppingBagDoubleBoFront", "name": "newShoppingBagDoubleBoFront", "category": "138839", "leaf": false},
            {"_id": "188805", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "newShoppingBagDoubleBoBack", "name": "newShoppingBagDoubleBoBack", "category": "138839", "leaf": false},
            {"_id": "188820", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "newShoppingBagSingleBo", "name": "newShoppingBagSingleBo", "category": "138839", "leaf": false},
            {"_id": "188821", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "newShoppingBagDobuleBo", "name": "newShoppingBagDobuleBo", "category": "138839", "leaf": false},
            {"_id": "188987", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Puzzle-square5*7", "name": "Puzzle-square5*7", "category": "188784", "leaf": true},
            {"_id": "188988", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Puzzle-square-card5*7", "name": "Puzzle-square-card5*7", "category": "188784", "leaf": true},
            {"_id": "188989", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Puzzle-square-envelope5*7", "name": "Puzzle-square-envelope5*7", "category": "188784", "leaf": true},
            {"_id": "189024", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "shoppingBagHandle", "name": "shoppingBagHandle", "category": "138839", "leaf": false},
            {"_id": "189315", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Puzzle", "name": "Puzzle", "category": "189314", "leaf": false},
            {"_id": "189316", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Card", "name": "Card", "category": "189314", "leaf": true},
            {"_id": "189317", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "FrameWhite_hang", "name": "FrameWhite_hang", "category": "189314", "leaf": true},
            {"_id": "189318", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "FrameWood_hang", "name": "FrameWood_hang", "category": "189314", "leaf": true},
            {"_id": "189319", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "FrameWhite_Up", "name": "FrameWhite_Up", "category": "189314", "leaf": true},
            {"_id": "189320", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "FrameWood_Up", "name": "FrameWood_Up", "category": "189314", "leaf": true},
            {"_id": "193765", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Round-puzzle", "name": "Round-puzzle", "category": "188784", "leaf": true},
            {"_id": "193775", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Round-puzzle-card", "name": "Round-puzzle-card", "category": "188784", "leaf": true},
            {"_id": "193776", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Round-puzzle-pack", "name": "Round-puzzle-pack", "category": "188784", "leaf": true},
            {"_id": "193783", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "shoppoingBagNew", "name": "shoppoingBagNew", "category": "138839", "leaf": true},
            {"_id": "179411", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "shoppoingBagNew", "name": "shoppoingBagNew", "category": "138839", "leaf": false},
            {"_id": "194481", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "heartShapedPuzzleBom", "name": "heartShapedPuzzleBom", "category": "194478", "leaf": true},
            {"_id": "194484", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "heartShapedPuzzle", "name": "heartShapedPuzzle", "category": "194478", "leaf": true},
            {"_id": "194485", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "heartShapedPuzzlePackage", "name": "heartShapedPuzzlePackage", "category": "194478", "leaf": true},
            {"_id": "194486", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "heartShapedPuzzlePhotoFrame", "name": "heartShapedPuzzlePhotoFrame", "category": "194478", "leaf": true},
            {"_id": "194553", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "invitationCardScodix", "name": "invitationCardScodix", "category": "133860", "leaf": true},
            {"_id": "196554", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PuzzleCard", "name": "PuzzleCard", "category": "188784", "leaf": true},
            {"_id": "196557", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "TopPuzzleBox", "name": "TopPuzzleBox", "category": "188784", "leaf": true},
            {"_id": "196560", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "BottomPuzzleBox", "name": "BottomPuzzleBox", "category": "188784", "leaf": true},
            {"_id": "196561", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PuzzleV2", "name": "PuzzleV2", "category": "188784", "leaf": false},
            {"_id": "196562", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PuzzleBoxV2", "name": "PuzzleBoxV2", "category": "188784", "leaf": true},
            {"_id": "196667", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test333", "name": "test333", "category": "144073", "leaf": false},
            {"_id": "197640", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PuzzleV3", "name": "PuzzleV3", "category": "188784", "leaf": false},
            {"_id": "197697", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PuzzleCardV3", "name": "PuzzleCardV3", "category": "188784", "leaf": false},
            {"_id": "197709", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PuzzleBoxV3", "name": "PuzzleBoxV3", "category": "188784", "leaf": false},
            {"_id": "197710", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "TopPuzzleBoxV3", "name": "TopPuzzleBoxV3", "category": "188784", "leaf": false},
            {"_id": "197793", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "RoundPuzzle", "name": "RoundPuzzle", "category": "188784", "leaf": false},
            {"_id": "197811", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "RoundPuzzleCard", "name": "RoundPuzzleCard", "category": "188784", "leaf": false},
            {"_id": "197813", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "RoundPuzzlePack", "name": "RoundPuzzlePack", "category": "188784", "leaf": true},
            {"_id": "201300", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PhotoFrame8x10", "name": "PhotoFrame8x10", "category": "201293", "leaf": false},
            {"_id": "204365", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "gameTilesBom", "name": "gameTilesBom", "category": "193402", "leaf": false},
            {"_id": "206076", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "NewRoundPuzzle", "name": "NewRoundPuzzle", "category": "188784", "leaf": false},
            {"_id": "206087", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "NewRoundPuzzlePack", "name": "NewRoundPuzzlePack", "category": "188784", "leaf": true},
            {"_id": "206089", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "NewRoundPuzzleCard26", "name": "NewRoundPuzzleCard26", "category": "188784", "leaf": true},
            {"_id": "206091", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "NewRoundPuzzleCard72", "name": "NewRoundPuzzleCard72", "category": "188784", "leaf": true},
            {"_id": "206447", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Puzzle8x10_V4", "name": "Puzzle8x10_V4", "category": "188784", "leaf": false},
            {"_id": "206497", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PuzzleBox8x10_V4", "name": "PuzzleBox8x10_V4", "category": "188784", "leaf": false},
            {"_id": "206523", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PuzzleBoxTop_8x10_V4", "name": "PuzzleBoxTop_8x10_V4", "category": "188784", "leaf": false},
            {"_id": "207969", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PuzzleCard_12_8x10_V4", "name": "PuzzleCard_12_8x10_V4", "category": "188784", "leaf": true},
            {"_id": "207970", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PuzzleCard_100_8x10_V4", "name": "PuzzleCard_100_8x10_V4", "category": "188784", "leaf": true},
            {"_id": "207971", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PuzzleBoxBottom_8x10_V4", "name": "PuzzleBoxBottom_8x10_V4", "category": "188784", "leaf": true},
            {"_id": "210694", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Tray-puzzle", "name": "Tray-puzzle", "category": "210692", "leaf": false},
            {"_id": "210695", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Tray-puzzle-12card", "name": "Tray-puzzle-12card", "category": "210692", "leaf": true},
            {"_id": "210696", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Tray-puzzle-pack", "name": "Tray-puzzle-pack", "category": "210692", "leaf": true},
            {"_id": "210697", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Tray-puzzle-100card", "name": "Tray-puzzle-100card", "category": "210692", "leaf": true},
            {"_id": "225391", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Puzzle12x16", "name": "Puzzle12x16", "category": "188784", "leaf": false},
            {"_id": "225429", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PuzzleCard12x16_54", "name": "PuzzleCard12x16_54", "category": "188784", "leaf": true},
            {"_id": "225456", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PuzzleCard12x16_285", "name": "PuzzleCard12x16_285", "category": "188784", "leaf": true},
            {"_id": "225479", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PuzzleBox12x16", "name": "PuzzleBox12x16", "category": "188784", "leaf": false},
            {"_id": "225528", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PuzzleBoxTop12x16", "name": "PuzzleBoxTop12x16", "category": "188784", "leaf": false},
            {"_id": "225529", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PuzzleBoxBottom12x16", "name": "PuzzleBoxBottom12x16", "category": "188784", "leaf": true},
            {"_id": "225564", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Square puzzle12*16", "name": "Square puzzle12*16", "category": "210692", "leaf": false},
            {"_id": "225566", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Square puzzle12*16-54Card", "name": "Square puzzle12*16-54Card", "category": "210692", "leaf": true},
            {"_id": "225567", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Square puzzle12*16-285Card", "name": "Square puzzle12*16-285Card", "category": "210692", "leaf": true},
            {"_id": "225568", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Square puzzle12*16-TopBox", "name": "Square puzzle12*16-TopBox", "category": "210692", "leaf": false},
            {"_id": "225569", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Square puzzle12*16-BottomBox", "name": "Square puzzle12*16-BottomBox", "category": "210692", "leaf": true},
            {"_id": "225570", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Square puzzle12*16-Box", "name": "Square puzzle12*16-Box", "category": "210692", "leaf": false},
            {"_id": "228197", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "gameBoxBom", "name": "gameBoxBom", "category": "228192", "leaf": false},
            {"_id": "228198", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "gameBoxFront", "name": "gameBoxFront", "category": "228192", "leaf": true},
            {"_id": "228199", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "gameBoxBack", "name": "gameBoxBack", "category": "228192", "leaf": true},
            {"_id": "228593", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "hearShapePuzzleMagnetic", "name": "hearShapePuzzleMagnetic", "category": "194478", "leaf": true},
            {"_id": "231664", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "hearShapePuzzleMagneticBom", "name": "hearShapePuzzleMagneticBom", "category": "194478", "leaf": true},
            {"_id": "234017", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PhotoFrame12x16", "name": "PhotoFrame12x16", "category": "201293", "leaf": false},
            {"_id": "240420", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "puzzle-magnetism-8*10card-crosswise", "name": "puzzle-magnetism-8*10card-crosswise", "category": "210692", "leaf": false},
            {"_id": "240473", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "puzzle-magnetism-12card--crosswise", "name": "puzzle-magnetism-12card--crosswise", "category": "210692", "leaf": false},
            {"_id": "240478", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "puzzle-magnetism-100card--crosswise", "name": "puzzle-magnetism-100card--crosswise", "category": "210692", "leaf": true},
            {"_id": "240561", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "InvitationCardScodixBraille", "name": "InvitationCardScodixBraille", "category": "133860", "leaf": false},
            {"_id": "241097", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "MagneticPuzzle12x16", "name": "MagneticPuzzle12x16", "category": "188784", "leaf": false},
            {"_id": "241109", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "MagneticPuzzleCard12x16_54", "name": "MagneticPuzzleCard12x16_54", "category": "188784", "leaf": false},
            {"_id": "241120", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "MagneticPuzzleCard12x16_285", "name": "MagneticPuzzleCard12x16_285", "category": "188784", "leaf": true},
            {"_id": "242902", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "puzzle-magnetism-box--crosswise", "name": "puzzle-magnetism-box--crosswise", "category": "210692", "leaf": false},
            {"_id": "242903", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "puzzle-magnetism--topbox-crosswise", "name": "puzzle-magnetism--topbox-crosswise", "category": "210692", "leaf": false},
            {"_id": "242909", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "puzzle-magnetism--bottombox-crosswise", "name": "puzzle-magnetism--bottombox-crosswise", "category": "210692", "leaf": true},
            {"_id": "261277", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "gameBoardBom", "name": "gameBoardBom", "category": "259994", "leaf": false},
            {"_id": "264062", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "gameBoardNonFold", "name": "gameBoardNonFold", "category": "259994", "leaf": false},
            {"_id": "264069", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "gameBoardBiFold", "name": "gameBoardBiFold", "category": "259994", "leaf": false},
            {"_id": "264072", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "gameBoardZFold", "name": "gameBoardZFold", "category": "259994", "leaf": false},
            {"_id": "264075", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "gameBoardQuadFold", "name": "gameBoardQuadFold", "category": "259994", "leaf": false},
            {"_id": "264076", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "gameBoardTriFold", "name": "gameBoardTriFold", "category": "259994", "leaf": false},
            {"_id": "264085", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "105gBlackCover", "name": "105g\u9ed1\u8272\u4e66\u76ae\u7eb8", "category": "259994", "leaf": false},
            {"_id": "264092", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "128gDoublePinkFront", "name": "128g\u53cc\u7c89", "category": "259994", "leaf": false},
            {"_id": "264093", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "128gDoublePinkBack", "name": "128g\u53cc\u7c89", "category": "259994", "leaf": false},
            {"_id": "264094", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "mortarboard", "name": "\u7070\u677f", "category": "259994", "leaf": false},
            {"_id": "264614", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "dynamicSizeBox", "name": "dynamicSizeBox", "category": "264611", "leaf": false},
            {"_id": "264616", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "dynamicSizeBoxFront", "name": "dynamicSizeBoxFront", "category": "264611", "leaf": true},
            {"_id": "264618", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "dynamicSizeBoxBack", "name": "dynamicSizeBoxBack", "category": "264611", "leaf": true},
            {"_id": "272082", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "RoundPuzzleBox", "name": "RoundPuzzleBox", "category": "188784", "leaf": false},
            {"_id": "272086", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "RoundPuzzle-box", "name": "RoundPuzzle-box", "category": "188784", "leaf": false},
            {"_id": "272090", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "RoundPuzzleBox-26pcs", "name": "RoundPuzzleBox-26pcs", "category": "188784", "leaf": true},
            {"_id": "272114", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "RoundPuzzleBox-72pcs", "name": "RoundPuzzleBox-72pcs", "category": "188784", "leaf": true},
            {"_id": "272131", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "RoundPuzzleBox-topBox", "name": "RoundPuzzleBox-topBox", "category": "188784", "leaf": false},
            {"_id": "272132", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "RoundPuzzleBox-bottomBox", "name": "RoundPuzzleBox-bottomBox", "category": "188784", "leaf": true},
            {"_id": "280333", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "main", "name": "main", "category": "144073", "leaf": true},
            {"_id": "280334", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "one-12PCS", "name": "one-12PCS", "category": "144073", "leaf": true},
            {"_id": "280335", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "one-100PCS", "name": "one-100PCS", "category": "144073", "leaf": true},
            {"_id": "281171", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CustomTuckBoxBom", "name": "CustomTuckBoxBom", "category": "281166", "leaf": false},
            {"_id": "326008", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "qingf_test", "name": "qingf_test", "category": "326002", "leaf": false},
            {"_id": "326027", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "qingf_spu", "name": "qingf_spu", "category": "326002", "leaf": true},
            {"_id": "331734", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "A1CardPriceCard", "name": "A1CardPriceCard", "category": "331733", "leaf": false},
            {"_id": "331736", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "A1CardPriceCardRight", "name": "A1CardPriceCardRight", "category": "331733", "leaf": false},
            {"_id": "331737", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "A1CardPriceCardRound", "name": "A1CardPriceCardRound", "category": "331733", "leaf": false},
            {"_id": "340616", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CustomTuckBoxPaper270", "name": "CustomTuckBoxPaper270", "category": "281166", "leaf": false},
            {"_id": "340629", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CustomTuckBoxPaper300", "name": "CustomTuckBoxPaper300", "category": "281166", "leaf": true},
            {"_id": "340631", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CustomTuckBoxPaper310", "name": "CustomTuckBoxPaper310", "category": "281166", "leaf": true},
            {"_id": "340635", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CustomTuckBoxPaper330", "name": "CustomTuckBoxPaper330", "category": "281166", "leaf": true},
            {"_id": "340639", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CustomTuckBoxPaper310Air", "name": "CustomTuckBoxPaper310Air", "category": "281166", "leaf": true},
            {"_id": "340954", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CustomTuckBoxPaperPlastic", "name": "CustomTuckBoxPaperPlastic", "category": "281166", "leaf": true},
            {"_id": "376031", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "GameMatSticker", "name": "GameMatSticker", "category": "357584", "leaf": true},
            {"_id": "377420", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Material Mat 00", "name": "Material Mat 00", "category": "376022", "leaf": false},
            {"_id": "377433", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Material Mat", "name": "Material Mat", "category": "376022", "leaf": false},
            {"_id": "387994", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "1111", "name": "111", "category": "189314", "leaf": false},
            {"_id": "402338", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "tests", "name": "test", "category": "140677", "leaf": true},
            {"_id": "408727", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "testItem", "name": "testItem", "category": "144073", "leaf": true},
            {"_id": "408735", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "testItemOptionPartItem", "name": "testItemOptionPartItem", "category": "144073", "leaf": true},
            {"_id": "408738", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "testItemOptionPartItem2", "name": "testItemOptionPartItem2", "category": "144073", "leaf": true},
            {"_id": "408839", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "testItemFix", "name": "testItemFix", "category": "144073", "leaf": true},
            {"_id": "427755", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "QinYueMaterial", "name": "QinYueMaterial", "category": "427723", "leaf": false},
            {"_id": "427780", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "QinYuePaper", "name": "QinYue", "category": "427723", "leaf": false},
            {"_id": "430302", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "FancyBuilderBox", "name": "FancyBuilderBox", "category": "430288", "leaf": true},
            {"_id": "430437", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "GameMat", "name": "GameMat-T", "category": "376022", "leaf": false},
            {"_id": "430446", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GameMat", "name": "GameMat01", "category": "376022", "leaf": true},
            {"_id": "430450", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GameMat", "name": "GameMat02", "category": "376022", "leaf": true},
            {"_id": "430972", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "FancyBuilderBag", "name": "FancyBuilderBag", "category": "430292", "leaf": true},
            {"_id": "435530", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "shoppingBoxes", "name": "shoppingBoxes", "category": "435528", "leaf": true},
            {"_id": "457402", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "aaa", "name": "aa", "category": "376022", "leaf": true},
            {"_id": "457881", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Gift Box", "name": "Box", "category": "457875", "leaf": false},
            {"_id": "457895", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Gift Box", "name": "Gift Box", "category": "457875", "leaf": false},
            {"_id": "457906", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "ShoppingBag", "name": "ShoppingBags", "category": "457905", "leaf": false},
            {"_id": "457907", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "ShoppingBag", "name": "ShoppingBag", "category": "457905", "leaf": false},
            {"_id": "457908", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "ShoppingBag", "name": "ShoppingBagRope", "category": "457905", "leaf": false},
            {"_id": "469214", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "paper size", "name": "paper size", "category": "469103", "leaf": true},
            {"_id": "469215", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "size", "name": "size", "category": "469103", "leaf": true},
            {"_id": "469221", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "weddingSticker", "name": "weddingSticker", "category": "469220", "leaf": true},
            {"_id": "479309", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "ShoppingBagsFashion", "name": "ShoppingBagsFashion", "category": "457905", "leaf": false},
            {"_id": "479316", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "ShoppingFashionBag", "name": "ShoppingFashionBag", "category": "457905", "leaf": false},
            {"_id": "479482", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "weddingSticker1", "name": "weddingSticker1", "category": "469220", "leaf": true},
            {"_id": "480180", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CustomPaperShoppingBag", "name": "CustomPaperShoppingBags", "category": "457905", "leaf": false},
            {"_id": "480181", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CostomShoppingBagPaper", "name": "CostomShoppingBagPaper", "category": "457905", "leaf": false},
            {"_id": "483278", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "GiftBox", "name": "GiftBox", "category": "457875", "leaf": false},
            {"_id": "483520", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "GiftBox", "name": "GiftBox", "category": "457875", "leaf": false},
            {"_id": "486553", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "GiftBox-changeColor", "name": "GiftBox", "category": "457875", "leaf": false},
            {"_id": "486554", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "GiftBox-changeColor", "name": "GiftBox", "category": "457875", "leaf": false},
            {"_id": "487445", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test6661", "name": "test6661", "category": "144073", "leaf": true},
            {"_id": "491397", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "A18", "name": "A18", "category": "491392", "leaf": true},
            {"_id": "491398", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "A20", "name": "A20", "category": "491392", "leaf": true},
            {"_id": "491399", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "A2012", "name": "A2012", "category": "491392", "leaf": true},
            {"_id": "494212", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "201330330124", "name": "phone", "category": "494206", "leaf": true},
            {"_id": "494447", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "cupbody", "name": "CupBody", "category": "494444", "leaf": true},
            {"_id": "494448", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "cupcover", "name": "CupCover", "category": "494444", "leaf": true},
            {"_id": "494449", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "ribbon", "name": "CupRibbon", "category": "494445", "leaf": true},
            {"_id": "494450", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "cupliips", "name": "CupLips", "category": "494446", "leaf": true},
            {"_id": "494455", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "pen gai", "name": "pen gai", "category": "494453", "leaf": true},
            {"_id": "494457", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "pen shen", "name": "pen shen", "category": "494456", "leaf": true},
            {"_id": "494460", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "pen xin", "name": "pen xin", "category": "494458", "leaf": true},
            {"_id": "494462", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "pen", "name": "pen", "category": "494461", "leaf": true},
            {"_id": "494463", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "pen test2", "name": "pen test2", "category": "494461", "leaf": false},
            {"_id": "496592", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "hm card", "name": "hm card", "category": "496588", "leaf": true},
            {"_id": "496594", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "hm ep", "name": "hm ep", "category": "496588", "leaf": true},
            {"_id": "497363", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "iphone", "name": "iPhone\u624b\u673a", "category": "494206", "leaf": true},
            {"_id": "497490", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "ScreenMatiral", "name": "\u624b\u673a\u5c4f\u5e55", "category": "494206", "leaf": true},
            {"_id": "497556", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "CPU", "name": "CPU", "category": "494206", "leaf": false},
            {"_id": "502835", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "WhiteboardPen", "name": "WhiteboardPen", "category": "502799", "leaf": true},
            {"_id": "502931", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Chalk", "name": "Chalk", "category": "502795", "leaf": true},
            {"_id": "502932", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Pen", "name": "Pen", "category": "502790", "leaf": true},
            {"_id": "502943", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PenBox", "name": "PenBox", "category": "502788", "leaf": true},
            {"_id": "517057", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "GF0120BDLP photo frame", "name": "GF0120BDLP photo frame", "category": "201293", "leaf": true},
            {"_id": "517121", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "photo frame", "name": "photo frame", "category": "201293", "leaf": true},
            {"_id": "517138", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "photos", "name": "photos", "category": "201293", "leaf": true},
            {"_id": "517171", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "transparent paper", "name": "transparent paper", "category": "201293", "leaf": true},
            {"_id": "545653", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0120BDLP", "name": "GF0120BDLP ", "category": "201293", "leaf": true},
            {"_id": "550689", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0143BVLP", "name": "GF0143BVLP", "category": "201293", "leaf": true},
            {"_id": "550779", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0143BVLP photo frame", "name": "GF0143BVLP photo frame", "category": "201293", "leaf": true},
            {"_id": "550780", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0143BVLP photos", "name": "GF0143BVLP photos", "category": "201293", "leaf": true},
            {"_id": "550787", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0143BVLP transparent paper", "name": "GF0143BVLP transparent paper", "category": "201293", "leaf": true},
            {"_id": "560677", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test", "name": "test", "category": "281166", "leaf": true},
            {"_id": "560833", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test-2", "name": "test-2", "category": "281166", "leaf": true},
            {"_id": "562635", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "GiftBox-ColorSizeChange", "name": "Gift Boxes", "category": "457875", "leaf": false},
            {"_id": "562642", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "GiftBox-ColorSizeChange", "name": "GiftBoxes", "category": "457875", "leaf": true},
            {"_id": "569992", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "hallmarkCard", "name": "hallmarkCard", "category": "569988", "leaf": true},
            {"_id": "570071", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "qpBox", "name": "qpBox", "category": "570066", "leaf": true},
            {"_id": "580737", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test", "name": "test", "category": "138839", "leaf": true},
            {"_id": "595355", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "hallmarkJoyCard", "name": "hallmarkJoyCard", "category": "595354", "leaf": true},
            {"_id": "595356", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "hallmarkJoyCardPaper", "name": "hallmarkJoyCardPaper", "category": "595354", "leaf": true},
            {"_id": "595362", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "hallmarkJoyBasePaper", "name": "hallmarkJoyBasePaper", "category": "595354", "leaf": true},
            {"_id": "595364", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "hallmarkJoyInsertPaper", "name": "hallmarkJoyInsertPaper", "category": "595354", "leaf": true},
            {"_id": "595380", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "joyTipOn", "name": "joyTipOn", "category": "595354", "leaf": true},
            {"_id": "595382", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Accessories", "name": "Accessories", "category": "595354", "leaf": true},
            {"_id": "595383", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Envelope", "name": "Envelope", "category": "595354", "leaf": true},
            {"_id": "595384", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PID", "name": "PID", "category": "595354", "leaf": true},
            {"_id": "595385", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Packing", "name": "Packing", "category": "595354", "leaf": true},
            {"_id": "602065", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0802AKLP", "name": "GF0802AKLP", "category": "201293", "leaf": true},
            {"_id": "602067", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0802AKLP photo frame", "name": "GF0802AKLP photo frame", "category": "201293", "leaf": true},
            {"_id": "602069", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0802AKLP photos", "name": "GF0802AKLP photos", "category": "201293", "leaf": true},
            {"_id": "602071", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0802AKLP transparent paper", "name": "GF0802AKLP transparent paper", "category": "201293", "leaf": true},
            {"_id": "604918", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0803BHLP", "name": "GF0803BHLP", "category": "201293", "leaf": true},
            {"_id": "604924", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0803BHLP photo frame", "name": "GF0803BHLP photo frame", "category": "201293", "leaf": true},
            {"_id": "604925", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0803BHLP photos", "name": " GF0803BHLP photos", "category": "201293", "leaf": true},
            {"_id": "604928", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0803BHLP transparen paper", "name": "GF0803BHLP transparen paper", "category": "201293", "leaf": true},
            {"_id": "610682", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "shoppingBagCPB", "name": "shoppingBag_CPB", "category": "138839", "leaf": false},
            {"_id": "610937", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "shoppingBag_CPBHandle", "name": "shoppingBag_CPBHandle", "category": "138839", "leaf": false},
            {"_id": "610943", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "shoppingBagCPBBody", "name": "shoppingBagCPBBody", "category": "138839", "leaf": false},
            {"_id": "614269", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "test", "name": "test", "category": "144073", "leaf": true},
            {"_id": "614837", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Body", "name": "Body", "category": "138839", "leaf": false},
            {"_id": "614849", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Handle", "name": "Handle", "category": "138839", "leaf": false},
            {"_id": "614862", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "ShoppingBag_V1", "name": "ShoppingBag_V1", "category": "138839", "leaf": false},
            {"_id": "640261", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "card stock and box", "name": "playing card (card + box)", "category": "636377", "leaf": true},
            {"_id": "640268", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "card stock", "name": "\u5361\u724c", "category": "636377", "leaf": true},
            {"_id": "640772", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PC", "name": "PC", "category": "640754", "leaf": true},
            {"_id": "640774", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PC-card", "name": "\u5361\u724c", "category": "640754", "leaf": true},
            {"_id": "640777", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "PC-box", "name": "\u76d2\u5b50", "category": "640754", "leaf": true},
            {"_id": "642245", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingCardPokerOil", "name": "playingCardPokerOil", "category": "642233", "leaf": true},
            {"_id": "642264", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingCardTestCard", "name": "playingCardTestCard", "category": "642256", "leaf": true},
            {"_id": "642298", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingCardPaper", "name": "playingCardPaper", "category": "642256", "leaf": true},
            {"_id": "642506", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Playingcard_card", "name": "Playingcard_card", "category": "642443", "leaf": true},
            {"_id": "643076", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingcard_box", "name": "playingcard_box", "category": "643070", "leaf": true},
            {"_id": "643091", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingcard", "name": "playingcard", "category": "643090", "leaf": true},
            {"_id": "643208", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingcard_Instructions", "name": "playingcard_Instructions", "category": "643206", "leaf": true},
            {"_id": "643891", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingcard_sticker", "name": "playingcard_sticker", "category": "643890", "leaf": true},
            {"_id": "644161", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingcard_Packing", "name": "playingcard_Packing", "category": "644148", "leaf": true},
            {"_id": "644895", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Playingcard_cardstock", "name": "Playingcard_cardstock", "category": "642443", "leaf": true},
            {"_id": "644903", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "Playingcard_cardfinish", "name": "Playingcard_cardfinish", "category": "642443", "leaf": true},
            {"_id": "644940", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingcard_cardprinttype", "name": "playingcard_cardprinttype", "category": "642443", "leaf": true},
            {"_id": "644941", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingcard_cardface", "name": "playingcard_cardface", "category": "642443", "leaf": true},
            {"_id": "645093", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_boxtype", "name": "palyingcard_boxtype", "category": "643070", "leaf": true},
            {"_id": "645097", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_boxtfinish", "name": "palyingcard_boxtfinish", "category": "643070", "leaf": true},
            {"_id": "645121", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "palyingcard_digitalbaseoil", "name": "palyingcard_digitalbaseoil", "category": "642443", "leaf": true},
            {"_id": "645122", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "palyingcard_shrinkage", "name": "palyingcard_shrinkage", "category": "642443", "leaf": true},
            {"_id": "645127", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "palyingcard_shrinkage", "name": "palyingcard_shrinkage", "category": "643070", "leaf": true},
            {"_id": "645128", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "palyingcard_digitalbaseoil", "name": "palyingcard_digitalbaseoil", "category": "643070", "leaf": true},
            {"_id": "645129", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "palyingcard_boxglue", "name": "palyingcard_boxglue", "category": "643070", "leaf": true},
            {"_id": "645135", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_instructionspaper", "name": "palyingcard_instructionspaper", "category": "643206", "leaf": true},
            {"_id": "645138", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_instructionsfinish", "name": "palyingcard_instructionsfinish", "category": "643206", "leaf": true},
            {"_id": "645141", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_stickerpaper", "name": "palyingcard_stickerpaper", "category": "643890", "leaf": true},
            {"_id": "645143", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_stickerfinish", "name": "palyingcard_stickerfinish", "category": "643890", "leaf": true},
            {"_id": "645145", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_box", "name": "palyingcard_box", "category": "643090", "leaf": true},
            {"_id": "645146", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_instructions", "name": "palyingcard_instructions", "category": "643090", "leaf": true},
            {"_id": "645148", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_sticker", "name": "palyingcard_sticker", "category": "643090", "leaf": true},
            {"_id": "645149", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_packaging", "name": "palyingcard_packaging", "category": "643090", "leaf": true},
            {"_id": "645150", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_packaging_bag", "name": "palyingcard_packaging_bag", "category": "644148", "leaf": true},
            {"_id": "645154", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_packaging_pitbox", "name": "palyingcard_packaging_pitbox", "category": "644148", "leaf": true},
            {"_id": "645157", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "palyingcard_packaging_bigpitbox", "name": "palyingcard_packaging_bigpitbox", "category": "644148", "leaf": true},
            {"_id": "645358", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "rere", "name": "\u70ed\u70ed", "category": "436145", "leaf": true},
            {"_id": "645918", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "playingcard_card", "name": "playingcard_card", "category": "643090", "leaf": true},
            {"_id": "645930", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0146BXLP photo frame", "name": "GF0146BXLP photo frame", "category": "201293", "leaf": true},
            {"_id": "645936", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0146BXLP photos", "name": "GF0146BXLP photos", "category": "201293", "leaf": true},
            {"_id": "645946", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0146BXLP transparen paper", "name": "GF0146BXLP transparen paper", "category": "201293", "leaf": true},
            {"_id": "646053", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GF0146BXLP", "name": "GF0146BXLP", "category": "201293", "leaf": true},
            {"_id": "647723", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "56", "name": "56", "category": "188784", "leaf": true},
            {"_id": "648877", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "1", "name": "1", "category": "648793", "leaf": true},
            {"_id": "648975", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "2", "name": "2", "category": "648793", "leaf": true},
            {"_id": "648978", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "3", "name": "3", "category": "648793", "leaf": true},
            {"_id": "649339", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "1", "name": "1", "category": "393848", "leaf": true},
            {"_id": "649747", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Card", "name": "Card", "category": "649725", "leaf": true},
            {"_id": "649748", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Accessories", "name": "Accessories", "category": "649725", "leaf": true},
            {"_id": "649752", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Envelope", "name": "Envelope", "category": "649725", "leaf": true},
            {"_id": "649753", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PID", "name": "PID", "category": "649725", "leaf": true},
            {"_id": "649754", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Packing", "name": "Packing", "category": "649725", "leaf": true},
            {"_id": "649758", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "base paper", "name": "base paper", "category": "649725", "leaf": true},
            {"_id": "649763", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "tip on paper", "name": "tip on paper", "category": "649725", "leaf": true},
            {"_id": "649767", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "559T1951", "name": "559T1951", "category": "649725", "leaf": true},
            {"_id": "651312", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GameTileBom", "name": "GameTileBom", "category": "651311", "leaf": true},
            {"_id": "670683", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "ard", "name": "card", "category": "670620", "leaf": true},
            {"_id": "670684", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "cars11", "name": "card11", "category": "670620", "leaf": true},
            {"_id": "671156", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "599MNN1069", "name": "599MNN1069", "category": "671152", "leaf": true},
            {"_id": "671158", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Card", "name": "Card", "category": "671152", "leaf": true},
            {"_id": "671161", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Accessories", "name": "Accessories", "category": "671152", "leaf": true},
            {"_id": "671162", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Envelope", "name": "Envelope", "category": "671152", "leaf": true},
            {"_id": "671163", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "PID", "name": "PID", "category": "671152", "leaf": true},
            {"_id": "671175", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Packing", "name": "Packing", "category": "671152", "leaf": true},
            {"_id": "671189", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Base Paper", "name": "Base Paper", "category": "671152", "leaf": true},
            {"_id": "672126", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "Cat Card", "name": "Cat Card", "category": "672099", "leaf": true},
            {"_id": "672130", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "gobletBasePaper", "name": "gobletBasePaper", "category": "672127", "leaf": true},
            {"_id": "672132", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "CatCard", "name": "CatCard", "category": "672099", "leaf": true},
            {"_id": "672135", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "CatAccessories", "name": "Accessories", "category": "672099", "leaf": true},
            {"_id": "672136", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "CatEnvelope", "name": "Envelope", "category": "672099", "leaf": true},
            {"_id": "672137", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "gobletInsertPaper", "name": "gobletInsertPaper", "category": "672127", "leaf": true},
            {"_id": "672138", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "CatPID", "name": "PID", "category": "672099", "leaf": true},
            {"_id": "672139", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "gobletICard", "name": "gobletICard", "category": "672127", "leaf": true},
            {"_id": "672140", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "CatPacking", "name": "Packing", "category": "672099", "leaf": true},
            {"_id": "672171", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "gobletIEnvelope", "name": "Envelope", "category": "672127", "leaf": true},
            {"_id": "672172", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "CatBasePaper", "name": "CatBasePaper", "category": "672099", "leaf": true},
            {"_id": "672173", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "gobletIAccessories", "name": "Accessories", "category": "672127", "leaf": true},
            {"_id": "672176", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "gobletIPID", "name": "PID", "category": "672127", "leaf": true},
            {"_id": "672177", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "gobletIPacking", "name": "Packing", "category": "672127", "leaf": true},
            {"_id": "672197", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "web2printGoblet", "name": "web2printGoblet", "category": "672127", "leaf": true},
            {"_id": "673060", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "daughterCard", "name": "Card", "category": "673059", "leaf": true},
            {"_id": "673061", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "daughterAccessories", "name": "Accessories", "category": "673059", "leaf": true},
            {"_id": "673063", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "daughterEnvelope", "name": "Envelope", "category": "673059", "leaf": true},
            {"_id": "673064", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "daughterPID", "name": "PID", "category": "673059", "leaf": true},
            {"_id": "673065", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "daughterPacking", "name": "Packing", "category": "673059", "leaf": true},
            {"_id": "673067", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "web2pritDaughterCard", "name": "web2pritDaughterCard", "category": "673059", "leaf": true},
            {"_id": "673069", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "daughterBasePaper", "name": "BasePaper", "category": "673059", "leaf": true},
            {"_id": "673071", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "daughterInsertPaper", "name": "InsertPaper", "category": "673059", "leaf": true},
            {"_id": "673462", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "dogCard", "name": "Card", "category": "673455", "leaf": true},
            {"_id": "673463", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "dogEnvelope", "name": "Envelope", "category": "673455", "leaf": true},
            {"_id": "673465", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "dogPID", "name": "PID", "category": "673455", "leaf": true},
            {"_id": "673466", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "dogPacking", "name": "Packing", "category": "673455", "leaf": true},
            {"_id": "673469", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "dogBasePaper", "name": "BasePaper", "category": "673455", "leaf": true},
            {"_id": "673473", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "DogCard", "name": "DogCard", "category": "673455", "leaf": true},
            {"_id": "673609", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "WineglassCard", "name": "web2pritWineglassCard", "category": "673607", "leaf": true},
            {"_id": "673612", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "WineglassCard", "name": "Card", "category": "673607", "leaf": true},
            {"_id": "673620", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "WineglassBasePaper", "name": "BasePaper", "category": "673607", "leaf": true},
            {"_id": "673623", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "WineglassTipOnPaper", "name": "TipOnPaper", "category": "673607", "leaf": true},
            {"_id": "673624", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "WineglassAccessories", "name": "Accessories", "category": "673607", "leaf": true},
            {"_id": "673626", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "WineglassEnvelope", "name": "Envelope", "category": "673607", "leaf": true},
            {"_id": "673633", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "WineglassPID", "name": "PID", "category": "673607", "leaf": true},
            {"_id": "673635", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "WineglassPacking", "name": "Packing", "category": "673607", "leaf": true},
            {"_id": "673931", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "GoldenCard", "name": "GoldenCard", "category": "673921", "leaf": true},
            {"_id": "673932", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "goldenCard", "name": "Card", "category": "673921", "leaf": true},
            {"_id": "673934", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "goldenAccessories", "name": "Accessories", "category": "673921", "leaf": true},
            {"_id": "673939", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "goldenEnvelope", "name": "Envelope", "category": "673921", "leaf": true},
            {"_id": "673940", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "goldenPID", "name": "PID", "category": "673921", "leaf": true},
            {"_id": "673945", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "goldenPacking", "name": "Packing", "category": "673921", "leaf": true},
            {"_id": "673946", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "goldenBasePaper", "name": "BasePaper", "category": "673921", "leaf": true},
            {"_id": "674132", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "dogCardAccessories", "name": "Accessories", "category": "673455", "leaf": true},
            {"_id": "675749", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "loveCardPaper", "name": "Card", "category": "675745", "leaf": true},
            {"_id": "675750", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "loveCardBasePaper", "name": "BasePaper", "category": "675745", "leaf": true},
            {"_id": "675751", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "loveCardInsertPaper", "name": "InsertPaper", "category": "675745", "leaf": true},
            {"_id": "675755", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "loveCardAccessories", "name": "Accessories", "category": "675745", "leaf": true},
            {"_id": "675756", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "loveCardEnvelope", "name": "Envelope", "category": "675745", "leaf": true},
            {"_id": "675757", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "loveCardPID", "name": "PID", "category": "675745", "leaf": true},
            {"_id": "675758", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "loveCardPacking", "name": "Packing", "category": "675745", "leaf": true},
            {"_id": "675759", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "web2printloveCard", "name": "web2printloveCard", "category": "675745", "leaf": true},
            {"_id": "675918", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "holidayBase", "name": "BasePaper", "category": "675916", "leaf": true},
            {"_id": "675919", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "holidayInsert", "name": "InsertPaper", "category": "675916", "leaf": true},
            {"_id": "675920", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "holidayTipOn", "name": "TipOn", "category": "675916", "leaf": true},
            {"_id": "675921", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "holidayCard", "name": "Card", "category": "675916", "leaf": true},
            {"_id": "675923", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "holidayAccess", "name": "Accessories", "category": "675916", "leaf": true},
            {"_id": "675924", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "holidayEnvelope", "name": "Envelope", "category": "675916", "leaf": true},
            {"_id": "675925", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "holidayPID", "name": "PID", "category": "675916", "leaf": true},
            {"_id": "675926", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "holidayPacking", "name": "Packing", "category": "675916", "leaf": true},
            {"_id": "675928", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "holidayProduct", "name": "holidayProductCard", "category": "675916", "leaf": true},
            {"_id": "676063", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "leafCard", "name": "leafCard", "category": "676062", "leaf": true},
            {"_id": "676064", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "leafBasePaper", "name": "BasePaper", "category": "676062", "leaf": true},
            {"_id": "676066", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "leafInsertPaper", "name": "InsertPaper", "category": "676062", "leaf": true},
            {"_id": "676067", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "leafAccess", "name": "Accessories", "category": "676062", "leaf": true},
            {"_id": "676068", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "leafEnvelope", "name": "Envelope", "category": "676062", "leaf": true},
            {"_id": "676069", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "leafPID", "name": "PID", "category": "676062", "leaf": true},
            {"_id": "676071", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "leafPacking", "name": "Packing", "category": "676062", "leaf": true},
            {"_id": "676072", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "leafProduct", "name": "leafProduct", "category": "676062", "leaf": true},
            {"_id": "676155", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "MagicBasePaper", "name": "BasePaper", "category": "676154", "leaf": true},
            {"_id": "676156", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "MagicCard", "name": "MagicCard", "category": "676154", "leaf": true},
            {"_id": "676157", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "MagicAccess", "name": "Accessories", "category": "676154", "leaf": true},
            {"_id": "676158", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "MagicEnvelope", "name": "Envelope", "category": "676154", "leaf": true},
            {"_id": "676159", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "MagicPID", "name": "PID", "category": "676154", "leaf": true},
            {"_id": "676160", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "MagicPacking", "name": "Packing", "category": "676154", "leaf": true},
            {"_id": "676161", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "MagicProduct", "name": "MagicProduct", "category": "676154", "leaf": true},
            {"_id": "679252", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "BoxOuter", "name": "Outer", "category": "679045", "leaf": true},
            {"_id": "679253", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "BoxTop", "name": "Top", "category": "679045", "leaf": true},
            {"_id": "679255", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "BoxBottom", "name": "Bottom", "category": "679045", "leaf": true},
            {"_id": "679257", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "BoxInterior", "name": "Interior", "category": "679045", "leaf": true},
            {"_id": "679278", "clazz": "com.qpp.cgp.domain.bom.MaterialType", "code": "FancyBuilderBox", "name": "Box", "category": "679045", "leaf": false},
            {"_id": "681783", "clazz": "com.qpp.cgp.domain.bom.MaterialSpu", "code": "BoxInteriorDesign", "name": "InteriorDesign", "category": "679045", "leaf": true}
        ]
    }
})