/**
 * Created by nan on 2021/8/30
 */
Ext.define('CGP.pagecontentschema.config.Config', {
    statics: {
        resource: {
            "filePath": "filePath",
            "jsonPath": "jsonPath",
            "name": "名称",
            "product": "产品",
            "qty": "数量",
            "information": "信息",
            "description": "描述",
            "code": "代码",
            "width": "宽",
            "height": "高",
            "clipPath": "clipPath",
            "d": "d",
            "cx": "cx",
            "cy": "cy",
            "rx": "rx",
            "ry": "ry",
            "r": "r",
            "x": "x",
            "y": "y",
            "type": "类型",
            "id": "编号",
            "is": "是否",
            "show": "显示",
            "true": "是",
            "false": "否",
            "layers": "layers",
            "add": "添加",
            "layer": "layer",
            "expandAll": "展开",
            "clazz": "类型",
            "save": "保存",
            "copy": "复制",
            "操作JSON数据": "操作JSON数据",
            "canvas": "canvas",
            "_id": "_id",
            "readOnly": "只读",
            "alpha": "alpha",
            "标签组": "标签组",
            "rotation": "rotation",
            "scale": "scale",
            "zIndex": "图层顺序",
            "text": "text",
            "technology": "工艺",
            "刺绣": "刺绣",
            "print": "打印",
            "textFileName": "textFileName",
            "path": "路径",
            "originalWidth": "originalWidth",
            "originalHeight": "originalHeight",
            "printFile": "printFile",
            "imageName": "imageName",
            "displayName": "显示名称",
            "contentTransform": "图片转换",
            "transform": '内容转换',
            "oringinal FileName": "oringinal FileName",
            "templateConfig GroupId": "templateConfig GroupId",
            "placeholder": "占位符",
            "imageWidth": "imageWidth",
            "imageHeight": "imageHeight",
            "shape": "形状",
            "fillStyle": "fillStyle",
            "color": "颜色",
            "10进制代码": "10进制代码",
            "value": "值",
            "显示颜色": "显示颜色",
            "noData": "没有数据！",
            "strokeStyle": "strokeStyle",
            "caps": "caps",
            "joints": "joints",
            "miterLimit": "miterLimit",
            "font": "字体",
            "fontFamily": "fontFamily",
            "fontSize": "fontSize",
            "fontStyle": "fontStyle",
            "normal (浏览器会显示一个标准的字体样式)": "normal (浏览器会显示一个标准的字体样式)",
            "italic (浏览器会显示一个斜体的字体样式)": "italic (浏览器会显示一个斜体的字体样式)",
            "oblique (浏览器会显示一个倾斜的字体样式)": "oblique (浏览器会显示一个倾斜的字体样式)",
            "embellishment": "装饰",
            "none (标准文本)": "none (标准文本)",
            "underline (带下划线的文本)": "underline (带下划线的文本)",
            "overline (上方带一直线的文本)": "overline (上方带一直线的文本)",
            "line-through (中间穿过一直线的文本)": "line-through (中间穿过一直线的文本)",
            "blink (闪烁的文本)": "blink (闪烁的文本)",
            "font-weight": "font-weight",
            "normal (标准的字符)": "normal (标准的字符)",
            "bold (粗体字符)": "bold (粗体字符)",
            "bolder (更粗的字符)": "bolder (更粗的字符)",
            "lighter (更细的字符)": "lighter (更细的字符)",
            "文本方向": "文本方向",
            "horizontal (水平方向内容自上而下)": "horizontal (水平方向内容自上而下)",
            "vertical-rl (垂直方向内容自右到左)": "vertical-rl (垂直方向内容自右到左)",
            "vertical-lr (垂直方向内容从上到下，水平方向从左到右)": "vertical-lr (垂直方向内容从上到下，水平方向从左到右)",
            "colorSource": "colorSource",
            "upload": "上传",
            "download": "下载",
            "topMargin": "topMargin",
            "bottomMargin": "bottomMargin",
            "leftMargin": "leftMargin",
            "rightMargin": "rightMargin",
            "Printing": "Printing",
            "Laser": "Laser",
            "GoldFoilStamping": "GoldFoilStamping",
            "SilverFoilStamping": "SilverFoilStamping",
            "Embroidery": "Embroidery",
            "UV": "UV",
            "Embossing": "Embossing",
            "Glittering": "Glittering",
            "Carve": "Carve",
            "effectType": "effectType",
            "新建": "新建",
            "Container": "Container",
            "lastStep": "上一步",
            "ok": "确定",
            "cancel": "取消",
            'horizontalAlign': '水平对齐方式',
            'verticalAlign': '垂直对齐方式'
        },
        mapping: {
            common: ['alpha', 'clazz', '_id', 'readOnly', 'description', 'tags', 'visible', 'x', 'y',
                'width', 'height', 'rotation', 'clipPath',/* 'effectType',*/ 'scale', 'zIndex', 'transform'],
            Container: ['readOnly'],
            TextPath: ['path', 'style', 'text'],
            Picture: ['imageName', 'originalName', 'originalWidth', 'originalHeight', 'printFile',
                'contentTransform', 'placeholder'/*, 'colorFilter'*/],
            Text: ['text', 'style'/*, 'type'*/],
            MultiLineText: ['text', 'style', /*'type',*/ 'textFileName'],
            UploadPicture: ['originalWidth', 'originalHeight', 'printFile', 'imageName', 'originalName', 'contentTransform',
                'placeholder', /*'colorFilter', */'displayName', 'originalFileName', 'templateConfigGroupId'],
            Image: ['imageName', 'imageWidth', 'imageHeight', 'printFile'],
            ShapeObject: ['shape', 'fillStyle', 'strokeStyle'],
            TextBlock: ['text', 'style', 'textFileName', 'fillStyle', 'horizontalAlign', 'verticalAlign']
        },
        displayObjectComponentList: [
            {
                value: 'Picture',
                display: 'Picture'
            },
            {
                value: 'Image',
                display: 'Image'
            },
            {
                value: 'Text',
                display: 'Text'
            },
            {
                value: 'ShapeObject',
                display: 'ShapeObject'
            },
            {
                value: 'MultiLineText',
                display: 'MultiLineText'
            },
            {
                value: 'UploadPicture',
                display: 'UploadPicture'
            },
            {
                value: 'TextPath',
                display: 'TextPath'
            },
            {
                value: 'TextBlock',
                display: 'TextBlock'
            }
        ]
    }
})

