/**
 * Created by nan on 2020/7/20.
 */
Ext.define('CGP.main.config.PageText', {
    statics: {
        data: {
            appName: 'CGP Management System',
            head: "CGP Management System",
            navigation: 'navigation',
            configuration: 'configuration area',
            bottom: "bottom area",
            userTree: "UserData",
            baseTree: "BaseData",
            langSelector: 'language',
            welcomeTab: 'welcome',
            customer: 'customer',
            role: 'role',
            language: 'language',
            currency: 'currency',
            productTree: 'product',
            product: 'product',
            productCategory: 'product category',
            country: 'country',
            zone: 'zone',
            taxrate: 'tax rate',
            website: 'website',
            configgroup: 'configgroup',
            systemConfig: 'system config',
            config: 'config',
            about: 'about',
            taxclass: 'tax class',
            attribute: 'attribute',
            attributeSet: 'attribute set',
            orderTree: 'Order',
            order: 'order',
            currentUser: 'Current User',
            userData: 'userData',
            baseData: 'baseData',
            maincategory: 'mainCategory',
            subcategory: 'subCategory',
            exit: 'Exit',
            greet: 'Welcome',
            source: 'Source',
            grouppermission: 'grouppermissinon',
            postage: 'postage',
            standardpostage: 'standardpostage',
            expresspostage: 'expresspostage',
            remotesurcharge: 'remotesurcharge',
            sfpostage: 'sfpostage',
            emspostage: 'emspostage',
            ztpostage: 'ztpostage',
            project: 'project',
            backgroundclass: 'backgroundclass',
            background: 'background',
            embellishment: "Embellishment",
            embellishmentclass: 'embellishmentclass',
            orderrefund: 'orderrefund',
            ordersalestatisticscompare: 'monthlysalestatisticscompare',
            productsalestatistics: 'productsalestatistics',
            prodcategorysale: 'prodcategorysale',
            monthsalestrend: 'monthsalestrend',
            monthsalesitepercentage: 'monthsalesitepercentage',
            finance: 'finance',
            ipnhistory: 'ipnhistory',
            loginToCGP: '登录' + websiteName,
            systemcache: 'System Cache',
            uat: "UserAccessTest",
            MANUFACTURE: 'MANUFACTURE',
            CS: 'CS',
            PSMOBILECN: 'PSMOBILECN',
            PSMOBILE: 'PSMOBILE',
            MPC: 'MPC',
            builderbackgroundclass: 'BuilderBackgroundClass',
            builderbackground: 'BuilderBackground',
            modifyPassword: 'modifyPassword'
        }    }
})
